AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for S3 for storing Gradle cache used in Buildkite CI"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: java-gradle-cache

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: java-gradle-cache
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "s3:*"
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:role/buildkite-Role"
            Resource:
              - arn:aws:s3:::java-gradle-cache
              - arn:aws:s3:::java-gradle-cache/*
