AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for Kinesis data stream and its related IAM managed policies"

Resources:
  ActivityPerformedDataStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: activity-performed
      RetentionPeriodHours: 24
      ShardCount: 1

  ActivityPerformedDataStreamConsumerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for creating a test database
      Path: /
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "kinesis:DescribeStream"
              - "kinesis:GetRecords"
              - "kinesis:GetShardIterator"
              - "kinesis:ListShards"
            Resource: !GetAtt ActivityPerformedDataStream.Arn
          - Effect: Allow
            Action:
              - "cloudwatch:PutMetricData"
            Resource: "*"

