AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for IAM role of EKS Service Account"

Resources:
  EksServiceAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: eks-raksit31667-ServiceAccountRole
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/oidc.eks.ap-southeast-1.amazonaws.com/id/98DE2C255095BD3D073BF2FA84F409B2"
            Action:
              - 'sts:AssumeRoleWithWebIdentity'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AdministratorAccess