steps:
  - label: ":aws-cloudformation: Deploy Cloudformation stacks"
    command: ./deploy.sh
    plugins:
      - cultureamp/aws-assume-role#v0.1.0:
          role: "arn:aws:iam::564702493239:role/ExampleSpringLoyaltyInfra"
    concurrency: 1
    concurrency_group: 'cloudformation'