AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for VPC peering connection of EKS and RDS"

Resources:
  VpcPeeringEksRds:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      PeerVpcId: vpc-e3488985
      VpcId: vpc-009589b536dbe9f14

  # Add route: All traffic to (destination) the EKS VPC CIDR block is via the VPC Peering Connection (target)
  VpcPeeringEksRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 10.0.0.0/24
      RouteTableId: rtb-037c996623b5a6fca
      VpcPeeringConnectionId: !Ref VpcPeeringEksRds