AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for RDS PostgreSQL for example-spring-loyalty"

Resources:
  ExampleSpringLoyaltyPostgreSQL:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: example-spring-loyalty-db
      DBName: ExampleSpringLoyalty
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      Engine: postgres
      EngineVersion: 13.3
      MasterUsername:
        Fn::Sub: "{{resolve:secretsmanager:${ExampleSpringLoyaltyPostgreSQLSecret}::username}}"
      MasterUserPassword:
        Fn::Sub: "{{resolve:secretsmanager:${ExampleSpringLoyaltyPostgreSQLSecret}::password}}"
      Port: 5432
      PubliclyAccessible: true
      StorageEncrypted: false
      VPCSecurityGroups:
        - !GetAtt ExampleSpringLoyaltyPostgreSQLSecurityGroup.GroupId
    DependsOn:
      - ExampleSpringLoyaltyPostgreSQLSecurityGroup

  ExampleSpringLoyaltyPostgreSQLSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: ExampleSpringLoyaltyPostgreSQLSecret
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\/?'

  ExampleSpringLoyaltyPostgreSQLSecretAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref ExampleSpringLoyaltyPostgreSQLSecret
      TargetId: !Ref ExampleSpringLoyaltyPostgreSQL
      TargetType: AWS::RDS::DBInstance

  ExampleSpringLoyaltyPostgreSQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ExampleSpringLoyaltyPostgreSQLSecurityGroup
      GroupDescription: Security group to whitelist access by IP

  ExampleSpringLoyaltyPostgreSQLLocalMachineWhitelist:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: 119.76.14.135/32
      Description: Used to restrict RDS public access to only my local machine
      FromPort: 5432
      ToPort: 5432
      IpProtocol: tcp
      GroupId: !GetAtt ExampleSpringLoyaltyPostgreSQLSecurityGroup.GroupId
    DependsOn: ExampleSpringLoyaltyPostgreSQLSecurityGroup

  ExampleSpringLoyaltyIngressTrafficFromEksToRdsWhitelist:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: 10.0.0.0/24
      Description: Used to allow all ingress traffic from the EKS cluster to the RDS instance
      FromPort: 5432
      ToPort: 5432
      IpProtocol: tcp
      GroupId: !GetAtt ExampleSpringLoyaltyPostgreSQLSecurityGroup.GroupId
    DependsOn: ExampleSpringLoyaltyPostgreSQLSecurityGroup

