AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for S3 for storing Gradle cache used in Buildkite CI"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: gradle-cache