AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for EC2 instance as a bastion host to connect private Amazon RDS"

Resources:
  ExampleSpringLoyaltyPostgreSQLBastionHost:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: example-spring-loyalty-db-bastion-host
      ImageId: ami-024221a59c9020e72 # https://github.com/widdix/aws-cf-templates/blob/master/vpc/vpc-ssh-bastion.yaml
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: example-spring-loyalty-db-bastion-host
      UserData:
        Fn::Base64: |
          function create_ssh_user() {
            local username="$1"
            local ssh_public_key="$2"
            adduser -m $username
            sudo su - $username << EOF
              mkdir .ssh
              chmod 700 .ssh
              touch .ssh/authorized_keys
              chmod 600 .ssh/authorized_keys
              echo $ssh_public_key > .ssh/authorized_keys
            EOF
          }

          usernames=(
            'raksit.man'
          )
          ssh_public_keys=(
            'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHIXfKDF8F1ed/v6EkABGBW9CO7nbB4823ISls4pvRHH2a4PuzSvZLsT3gIgcrJGNfSeAHm2+ltyBlN0jkMkCwjcLqvNAjTQDy6RT2Dkn6QZYRiKOQXQTPVUCmbfS8UK+vrpgqOjYlyOAT2CoggWcGLPywtF02pCpJZjMOfqzEyEw9o8VqEm5GoJAXvMqkBCNnKps9kODyAvYrWDEtMM9+hOzao1katPHrBoovJFfPA/PkCqewXqJ8X+DNVXMJ97+n2vLb8+XEyLUi93exyJWLS3/JBIbCsJnMtQrEJwtxmt8XcpL1OGwjF9DhvjRnCW7NUOjs+rL9eA0n2KCMKp1iF7954BrnVtOvg5IfQ4VpeUIm8hgqaorfl3GOwqgNVgEIimFMxMq8SsYF1P3dWoXCG7OUaD/8+zr24YKQNIrV3IkJ7elI45cj2WFvYrkZnpR96RiVES+yGPUXh6YLr0PkgvvNG1uYk2SgUfxjdDCWFRtQMej0CJoPebLHZgdSx0c= raksit.man@Raksits-MacBook-Pro.local'
          )

          for i in "${!usernames[@]}";
          do
            create_ssh_user "${usernames[i]}" "${ssh_public_keys[i]}" || true
          done

  ExampleSpringLoyaltyPostgreSQLBastionHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ExampleSpringLoyaltyPostgreSQLBastionHostSecurityGroup
      GroupDescription: Security group to whitelist access by IP

  ExampleSpringLoyaltyPostgreSQLBastionHostLocalMachineWhitelist:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      CidrIp: 119.76.15.162/32
      Description: Used to restrict bastion host public access to only my local machine
      FromPort: 22
      ToPort: 22
      IpProtocol: tcp
      GroupId: !GetAtt ExampleSpringLoyaltyPostgreSQLBastionHostSecurityGroup.GroupId

Outputs:
  ExampleSpringLoyaltyPostgreSQLBastionHostPrivateIP:
    Description: Private IP for example-spring-loyalty-db to allow bastion host access
    Value: !GetAtt ExampleSpringLoyaltyPostgreSQLBastionHost.PrivateIp
    Export:
      Name: ExampleSpringLoyaltyPostgreSQLBastionHostPrivateIP